FROM node:18.18.0-alpine3.18 as build

WORKDIR /app

COPY . .

WORKDIR /app/docusaurus

RUN yarn install
RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/docusaurus/build /usr/share/nginx/html/
