name: meilisearch

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Deploy docs to netlify"]
    types:
      - completed

jobs:
  indexing:
    runs-on: ubuntu-latest
    name: Meilisearch Indexing
    steps:
      - name: Pull and run container
        run: docker run -e CRAWLER_CONFIG="${CRAWLER_CONFIG}" getmeili/scrapix:v0.1.8
    env:
      CRAWLER_CONFIG: ${{ secrets.SCRAPIX_CONFIG }}
